/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */





declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  AccountCreateInput: { // input type
    accessToken?: string | null; // String
    accessTokenExpires?: NexusGenScalars['DateTime'] | null; // DateTime
    compoundId: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    providerAccountId: string; // String!
    providerId: string; // String!
    providerType: string; // String!
    refreshToken?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    userId: number; // Int!
  }
  AccountOrderByInput: { // input type
    accessToken?: NexusGenEnums['SortOrder'] | null; // SortOrder
    accessTokenExpires?: NexusGenEnums['SortOrder'] | null; // SortOrder
    compoundId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    providerAccountId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    providerId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    providerType?: NexusGenEnums['SortOrder'] | null; // SortOrder
    refreshToken?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    userId?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  AccountUpdateInput: { // input type
    accessToken?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    accessTokenExpires?: NexusGenInputs['NullableDateTimeFieldUpdateOperationsInput'] | null; // NullableDateTimeFieldUpdateOperationsInput
    compoundId?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    providerAccountId?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    providerId?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    providerType?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    refreshToken?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    userId?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
  }
  AccountUpdateManyMutationInput: { // input type
    accessToken?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    accessTokenExpires?: NexusGenInputs['NullableDateTimeFieldUpdateOperationsInput'] | null; // NullableDateTimeFieldUpdateOperationsInput
    compoundId?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    providerAccountId?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    providerId?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    providerType?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    refreshToken?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    userId?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
  }
  AccountWhereInput: { // input type
    accessToken?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    accessTokenExpires?: NexusGenInputs['DateTimeNullableFilter'] | null; // DateTimeNullableFilter
    AND?: NexusGenInputs['AccountWhereInput'][] | null; // [AccountWhereInput!]
    compoundId?: NexusGenInputs['StringFilter'] | null; // StringFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: NexusGenInputs['AccountWhereInput'][] | null; // [AccountWhereInput!]
    OR?: NexusGenInputs['AccountWhereInput'][] | null; // [AccountWhereInput!]
    providerAccountId?: NexusGenInputs['StringFilter'] | null; // StringFilter
    providerId?: NexusGenInputs['StringFilter'] | null; // StringFilter
    providerType?: NexusGenInputs['StringFilter'] | null; // StringFilter
    refreshToken?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    userId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  AccountWhereUniqueInput: { // input type
    compoundId?: string | null; // String
    id?: number | null; // Int
  }
  BoolFieldUpdateOperationsInput: { // input type
    set?: boolean | null; // Boolean
  }
  BoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  CharacterCreateInput: { // input type
    age?: number | null; // Int
    bloodType?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    eyes?: string | null; // String
    height?: string | null; // String
    name?: string | null; // String
    published?: boolean | null; // Boolean
    story: NexusGenInputs['StoryCreateNestedOneWithoutCharactersInput']; // StoryCreateNestedOneWithoutCharactersInput!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    weight?: string | null; // String
  }
  CharacterCreateNestedManyWithoutStoryInput: { // input type
    connect?: NexusGenInputs['CharacterWhereUniqueInput'][] | null; // [CharacterWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CharacterCreateOrConnectWithoutStoryInput'][] | null; // [CharacterCreateOrConnectWithoutStoryInput!]
    create?: NexusGenInputs['CharacterCreateWithoutStoryInput'][] | null; // [CharacterCreateWithoutStoryInput!]
  }
  CharacterCreateOrConnectWithoutStoryInput: { // input type
    create: NexusGenInputs['CharacterCreateWithoutStoryInput']; // CharacterCreateWithoutStoryInput!
    where: NexusGenInputs['CharacterWhereUniqueInput']; // CharacterWhereUniqueInput!
  }
  CharacterCreateWithoutStoryInput: { // input type
    age?: number | null; // Int
    bloodType?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    eyes?: string | null; // String
    height?: string | null; // String
    name?: string | null; // String
    published?: boolean | null; // Boolean
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    weight?: string | null; // String
  }
  CharacterListRelationFilter: { // input type
    every?: NexusGenInputs['CharacterWhereInput'] | null; // CharacterWhereInput
    none?: NexusGenInputs['CharacterWhereInput'] | null; // CharacterWhereInput
    some?: NexusGenInputs['CharacterWhereInput'] | null; // CharacterWhereInput
  }
  CharacterOrderByInput: { // input type
    age?: NexusGenEnums['SortOrder'] | null; // SortOrder
    bloodType?: NexusGenEnums['SortOrder'] | null; // SortOrder
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    description?: NexusGenEnums['SortOrder'] | null; // SortOrder
    eyes?: NexusGenEnums['SortOrder'] | null; // SortOrder
    height?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    published?: NexusGenEnums['SortOrder'] | null; // SortOrder
    story?: NexusGenInputs['StoryOrderByInput'] | null; // StoryOrderByInput
    storyId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    weight?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  CharacterScalarWhereInput: { // input type
    age?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    AND?: NexusGenInputs['CharacterScalarWhereInput'][] | null; // [CharacterScalarWhereInput!]
    bloodType?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    description?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    eyes?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    height?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    NOT?: NexusGenInputs['CharacterScalarWhereInput'][] | null; // [CharacterScalarWhereInput!]
    OR?: NexusGenInputs['CharacterScalarWhereInput'][] | null; // [CharacterScalarWhereInput!]
    published?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    storyId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    weight?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
  }
  CharacterUpdateInput: { // input type
    age?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    bloodType?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    eyes?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    height?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    story?: NexusGenInputs['StoryUpdateOneRequiredWithoutCharactersInput'] | null; // StoryUpdateOneRequiredWithoutCharactersInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    weight?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  CharacterUpdateManyMutationInput: { // input type
    age?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    bloodType?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    eyes?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    height?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    weight?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  CharacterUpdateManyWithWhereWithoutStoryInput: { // input type
    data: NexusGenInputs['CharacterUpdateManyMutationInput']; // CharacterUpdateManyMutationInput!
    where: NexusGenInputs['CharacterScalarWhereInput']; // CharacterScalarWhereInput!
  }
  CharacterUpdateManyWithoutStoryInput: { // input type
    connect?: NexusGenInputs['CharacterWhereUniqueInput'][] | null; // [CharacterWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CharacterCreateOrConnectWithoutStoryInput'][] | null; // [CharacterCreateOrConnectWithoutStoryInput!]
    create?: NexusGenInputs['CharacterCreateWithoutStoryInput'][] | null; // [CharacterCreateWithoutStoryInput!]
    delete?: NexusGenInputs['CharacterWhereUniqueInput'][] | null; // [CharacterWhereUniqueInput!]
    deleteMany?: NexusGenInputs['CharacterScalarWhereInput'][] | null; // [CharacterScalarWhereInput!]
    disconnect?: NexusGenInputs['CharacterWhereUniqueInput'][] | null; // [CharacterWhereUniqueInput!]
    set?: NexusGenInputs['CharacterWhereUniqueInput'][] | null; // [CharacterWhereUniqueInput!]
    update?: NexusGenInputs['CharacterUpdateWithWhereUniqueWithoutStoryInput'][] | null; // [CharacterUpdateWithWhereUniqueWithoutStoryInput!]
    updateMany?: NexusGenInputs['CharacterUpdateManyWithWhereWithoutStoryInput'][] | null; // [CharacterUpdateManyWithWhereWithoutStoryInput!]
    upsert?: NexusGenInputs['CharacterUpsertWithWhereUniqueWithoutStoryInput'][] | null; // [CharacterUpsertWithWhereUniqueWithoutStoryInput!]
  }
  CharacterUpdateWithWhereUniqueWithoutStoryInput: { // input type
    data: NexusGenInputs['CharacterUpdateWithoutStoryInput']; // CharacterUpdateWithoutStoryInput!
    where: NexusGenInputs['CharacterWhereUniqueInput']; // CharacterWhereUniqueInput!
  }
  CharacterUpdateWithoutStoryInput: { // input type
    age?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    bloodType?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    eyes?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    height?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    weight?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
  }
  CharacterUpsertWithWhereUniqueWithoutStoryInput: { // input type
    create: NexusGenInputs['CharacterCreateWithoutStoryInput']; // CharacterCreateWithoutStoryInput!
    update: NexusGenInputs['CharacterUpdateWithoutStoryInput']; // CharacterUpdateWithoutStoryInput!
    where: NexusGenInputs['CharacterWhereUniqueInput']; // CharacterWhereUniqueInput!
  }
  CharacterWhereInput: { // input type
    age?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    AND?: NexusGenInputs['CharacterWhereInput'][] | null; // [CharacterWhereInput!]
    bloodType?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    description?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    eyes?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    height?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    NOT?: NexusGenInputs['CharacterWhereInput'][] | null; // [CharacterWhereInput!]
    OR?: NexusGenInputs['CharacterWhereInput'][] | null; // [CharacterWhereInput!]
    published?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    story?: NexusGenInputs['StoryWhereInput'] | null; // StoryWhereInput
    storyId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    weight?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
  }
  CharacterWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  DateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  DateTimeNullableFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeNullableFilter'] | null; // NestedDateTimeNullableFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  IntFieldUpdateOperationsInput: { // input type
    decrement?: number | null; // Int
    divide?: number | null; // Int
    increment?: number | null; // Int
    multiply?: number | null; // Int
    set?: number | null; // Int
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  IntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedBoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedDateTimeNullableFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeNullableFilter'] | null; // NestedDateTimeNullableFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NullableDateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  NullableIntFieldUpdateOperationsInput: { // input type
    decrement?: number | null; // Int
    divide?: number | null; // Int
    increment?: number | null; // Int
    multiply?: number | null; // Int
    set?: number | null; // Int
  }
  NullableStringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  SeriesCreateInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    published?: boolean | null; // Boolean
    stories?: NexusGenInputs['StoryCreateNestedManyWithoutSeriesInput'] | null; // StoryCreateNestedManyWithoutSeriesInput
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  SeriesCreateNestedOneWithoutStoriesInput: { // input type
    connect?: NexusGenInputs['SeriesWhereUniqueInput'] | null; // SeriesWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SeriesCreateOrConnectWithoutStoriesInput'] | null; // SeriesCreateOrConnectWithoutStoriesInput
    create?: NexusGenInputs['SeriesCreateWithoutStoriesInput'] | null; // SeriesCreateWithoutStoriesInput
  }
  SeriesCreateOrConnectWithoutStoriesInput: { // input type
    create: NexusGenInputs['SeriesCreateWithoutStoriesInput']; // SeriesCreateWithoutStoriesInput!
    where: NexusGenInputs['SeriesWhereUniqueInput']; // SeriesWhereUniqueInput!
  }
  SeriesCreateWithoutStoriesInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    published?: boolean | null; // Boolean
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  SeriesOrderByInput: { // input type
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    description?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    published?: NexusGenEnums['SortOrder'] | null; // SortOrder
    title?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  SeriesUpdateInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    stories?: NexusGenInputs['StoryUpdateManyWithoutSeriesInput'] | null; // StoryUpdateManyWithoutSeriesInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  SeriesUpdateManyMutationInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  SeriesUpdateOneWithoutStoriesInput: { // input type
    connect?: NexusGenInputs['SeriesWhereUniqueInput'] | null; // SeriesWhereUniqueInput
    connectOrCreate?: NexusGenInputs['SeriesCreateOrConnectWithoutStoriesInput'] | null; // SeriesCreateOrConnectWithoutStoriesInput
    create?: NexusGenInputs['SeriesCreateWithoutStoriesInput'] | null; // SeriesCreateWithoutStoriesInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['SeriesUpdateWithoutStoriesInput'] | null; // SeriesUpdateWithoutStoriesInput
    upsert?: NexusGenInputs['SeriesUpsertWithoutStoriesInput'] | null; // SeriesUpsertWithoutStoriesInput
  }
  SeriesUpdateWithoutStoriesInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  SeriesUpsertWithoutStoriesInput: { // input type
    create: NexusGenInputs['SeriesCreateWithoutStoriesInput']; // SeriesCreateWithoutStoriesInput!
    update: NexusGenInputs['SeriesUpdateWithoutStoriesInput']; // SeriesUpdateWithoutStoriesInput!
  }
  SeriesWhereInput: { // input type
    AND?: NexusGenInputs['SeriesWhereInput'][] | null; // [SeriesWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    description?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: NexusGenInputs['SeriesWhereInput'][] | null; // [SeriesWhereInput!]
    OR?: NexusGenInputs['SeriesWhereInput'][] | null; // [SeriesWhereInput!]
    published?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    stories?: NexusGenInputs['StoryListRelationFilter'] | null; // StoryListRelationFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  SeriesWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  SessionCreateInput: { // input type
    accessToken: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    expires: NexusGenScalars['DateTime']; // DateTime!
    sessionToken: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    userId: number; // Int!
  }
  SessionOrderByInput: { // input type
    accessToken?: NexusGenEnums['SortOrder'] | null; // SortOrder
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    expires?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    sessionToken?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    userId?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  SessionUpdateInput: { // input type
    accessToken?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    expires?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    sessionToken?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    userId?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
  }
  SessionUpdateManyMutationInput: { // input type
    accessToken?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    expires?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    sessionToken?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    userId?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
  }
  SessionWhereInput: { // input type
    accessToken?: NexusGenInputs['StringFilter'] | null; // StringFilter
    AND?: NexusGenInputs['SessionWhereInput'][] | null; // [SessionWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    expires?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: NexusGenInputs['SessionWhereInput'][] | null; // [SessionWhereInput!]
    OR?: NexusGenInputs['SessionWhereInput'][] | null; // [SessionWhereInput!]
    sessionToken?: NexusGenInputs['StringFilter'] | null; // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    userId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  SessionWhereUniqueInput: { // input type
    accessToken?: string | null; // String
    id?: number | null; // Int
    sessionToken?: string | null; // String
  }
  StoryCreateInput: { // input type
    author: NexusGenInputs['UserCreateNestedOneWithoutStoriesInput']; // UserCreateNestedOneWithoutStoriesInput!
    characters?: NexusGenInputs['CharacterCreateNestedManyWithoutStoryInput'] | null; // CharacterCreateNestedManyWithoutStoryInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    part?: number | null; // Int
    private?: boolean | null; // Boolean
    published?: boolean | null; // Boolean
    series?: NexusGenInputs['SeriesCreateNestedOneWithoutStoriesInput'] | null; // SeriesCreateNestedOneWithoutStoriesInput
    subTitle?: string | null; // String
    thumbnail?: string | null; // String
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  StoryCreateNestedManyWithoutAuthorInput: { // input type
    connect?: NexusGenInputs['StoryWhereUniqueInput'][] | null; // [StoryWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['StoryCreateOrConnectWithoutAuthorInput'][] | null; // [StoryCreateOrConnectWithoutAuthorInput!]
    create?: NexusGenInputs['StoryCreateWithoutAuthorInput'][] | null; // [StoryCreateWithoutAuthorInput!]
  }
  StoryCreateNestedManyWithoutSeriesInput: { // input type
    connect?: NexusGenInputs['StoryWhereUniqueInput'][] | null; // [StoryWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['StoryCreateOrConnectWithoutSeriesInput'][] | null; // [StoryCreateOrConnectWithoutSeriesInput!]
    create?: NexusGenInputs['StoryCreateWithoutSeriesInput'][] | null; // [StoryCreateWithoutSeriesInput!]
  }
  StoryCreateNestedOneWithoutCharactersInput: { // input type
    connect?: NexusGenInputs['StoryWhereUniqueInput'] | null; // StoryWhereUniqueInput
    connectOrCreate?: NexusGenInputs['StoryCreateOrConnectWithoutCharactersInput'] | null; // StoryCreateOrConnectWithoutCharactersInput
    create?: NexusGenInputs['StoryCreateWithoutCharactersInput'] | null; // StoryCreateWithoutCharactersInput
  }
  StoryCreateOrConnectWithoutAuthorInput: { // input type
    create: NexusGenInputs['StoryCreateWithoutAuthorInput']; // StoryCreateWithoutAuthorInput!
    where: NexusGenInputs['StoryWhereUniqueInput']; // StoryWhereUniqueInput!
  }
  StoryCreateOrConnectWithoutCharactersInput: { // input type
    create: NexusGenInputs['StoryCreateWithoutCharactersInput']; // StoryCreateWithoutCharactersInput!
    where: NexusGenInputs['StoryWhereUniqueInput']; // StoryWhereUniqueInput!
  }
  StoryCreateOrConnectWithoutSeriesInput: { // input type
    create: NexusGenInputs['StoryCreateWithoutSeriesInput']; // StoryCreateWithoutSeriesInput!
    where: NexusGenInputs['StoryWhereUniqueInput']; // StoryWhereUniqueInput!
  }
  StoryCreateWithoutAuthorInput: { // input type
    characters?: NexusGenInputs['CharacterCreateNestedManyWithoutStoryInput'] | null; // CharacterCreateNestedManyWithoutStoryInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    part?: number | null; // Int
    private?: boolean | null; // Boolean
    published?: boolean | null; // Boolean
    series?: NexusGenInputs['SeriesCreateNestedOneWithoutStoriesInput'] | null; // SeriesCreateNestedOneWithoutStoriesInput
    subTitle?: string | null; // String
    thumbnail?: string | null; // String
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  StoryCreateWithoutCharactersInput: { // input type
    author: NexusGenInputs['UserCreateNestedOneWithoutStoriesInput']; // UserCreateNestedOneWithoutStoriesInput!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    part?: number | null; // Int
    private?: boolean | null; // Boolean
    published?: boolean | null; // Boolean
    series?: NexusGenInputs['SeriesCreateNestedOneWithoutStoriesInput'] | null; // SeriesCreateNestedOneWithoutStoriesInput
    subTitle?: string | null; // String
    thumbnail?: string | null; // String
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  StoryCreateWithoutSeriesInput: { // input type
    author: NexusGenInputs['UserCreateNestedOneWithoutStoriesInput']; // UserCreateNestedOneWithoutStoriesInput!
    characters?: NexusGenInputs['CharacterCreateNestedManyWithoutStoryInput'] | null; // CharacterCreateNestedManyWithoutStoryInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    part?: number | null; // Int
    private?: boolean | null; // Boolean
    published?: boolean | null; // Boolean
    subTitle?: string | null; // String
    thumbnail?: string | null; // String
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  StoryListRelationFilter: { // input type
    every?: NexusGenInputs['StoryWhereInput'] | null; // StoryWhereInput
    none?: NexusGenInputs['StoryWhereInput'] | null; // StoryWhereInput
    some?: NexusGenInputs['StoryWhereInput'] | null; // StoryWhereInput
  }
  StoryOrderByInput: { // input type
    author?: NexusGenInputs['UserOrderByInput'] | null; // UserOrderByInput
    authorId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    description?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    part?: NexusGenEnums['SortOrder'] | null; // SortOrder
    private?: NexusGenEnums['SortOrder'] | null; // SortOrder
    published?: NexusGenEnums['SortOrder'] | null; // SortOrder
    series?: NexusGenInputs['SeriesOrderByInput'] | null; // SeriesOrderByInput
    seriesId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    subTitle?: NexusGenEnums['SortOrder'] | null; // SortOrder
    thumbnail?: NexusGenEnums['SortOrder'] | null; // SortOrder
    title?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  StoryScalarWhereInput: { // input type
    AND?: NexusGenInputs['StoryScalarWhereInput'][] | null; // [StoryScalarWhereInput!]
    authorId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    description?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: NexusGenInputs['StoryScalarWhereInput'][] | null; // [StoryScalarWhereInput!]
    OR?: NexusGenInputs['StoryScalarWhereInput'][] | null; // [StoryScalarWhereInput!]
    part?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    private?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    published?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    seriesId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    subTitle?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    thumbnail?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  StoryUpdateInput: { // input type
    author?: NexusGenInputs['UserUpdateOneRequiredWithoutStoriesInput'] | null; // UserUpdateOneRequiredWithoutStoriesInput
    characters?: NexusGenInputs['CharacterUpdateManyWithoutStoryInput'] | null; // CharacterUpdateManyWithoutStoryInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    part?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    private?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    series?: NexusGenInputs['SeriesUpdateOneWithoutStoriesInput'] | null; // SeriesUpdateOneWithoutStoriesInput
    subTitle?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    thumbnail?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  StoryUpdateManyMutationInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    part?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    private?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    subTitle?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    thumbnail?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  StoryUpdateManyWithWhereWithoutAuthorInput: { // input type
    data: NexusGenInputs['StoryUpdateManyMutationInput']; // StoryUpdateManyMutationInput!
    where: NexusGenInputs['StoryScalarWhereInput']; // StoryScalarWhereInput!
  }
  StoryUpdateManyWithWhereWithoutSeriesInput: { // input type
    data: NexusGenInputs['StoryUpdateManyMutationInput']; // StoryUpdateManyMutationInput!
    where: NexusGenInputs['StoryScalarWhereInput']; // StoryScalarWhereInput!
  }
  StoryUpdateManyWithoutAuthorInput: { // input type
    connect?: NexusGenInputs['StoryWhereUniqueInput'][] | null; // [StoryWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['StoryCreateOrConnectWithoutAuthorInput'][] | null; // [StoryCreateOrConnectWithoutAuthorInput!]
    create?: NexusGenInputs['StoryCreateWithoutAuthorInput'][] | null; // [StoryCreateWithoutAuthorInput!]
    delete?: NexusGenInputs['StoryWhereUniqueInput'][] | null; // [StoryWhereUniqueInput!]
    deleteMany?: NexusGenInputs['StoryScalarWhereInput'][] | null; // [StoryScalarWhereInput!]
    disconnect?: NexusGenInputs['StoryWhereUniqueInput'][] | null; // [StoryWhereUniqueInput!]
    set?: NexusGenInputs['StoryWhereUniqueInput'][] | null; // [StoryWhereUniqueInput!]
    update?: NexusGenInputs['StoryUpdateWithWhereUniqueWithoutAuthorInput'][] | null; // [StoryUpdateWithWhereUniqueWithoutAuthorInput!]
    updateMany?: NexusGenInputs['StoryUpdateManyWithWhereWithoutAuthorInput'][] | null; // [StoryUpdateManyWithWhereWithoutAuthorInput!]
    upsert?: NexusGenInputs['StoryUpsertWithWhereUniqueWithoutAuthorInput'][] | null; // [StoryUpsertWithWhereUniqueWithoutAuthorInput!]
  }
  StoryUpdateManyWithoutSeriesInput: { // input type
    connect?: NexusGenInputs['StoryWhereUniqueInput'][] | null; // [StoryWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['StoryCreateOrConnectWithoutSeriesInput'][] | null; // [StoryCreateOrConnectWithoutSeriesInput!]
    create?: NexusGenInputs['StoryCreateWithoutSeriesInput'][] | null; // [StoryCreateWithoutSeriesInput!]
    delete?: NexusGenInputs['StoryWhereUniqueInput'][] | null; // [StoryWhereUniqueInput!]
    deleteMany?: NexusGenInputs['StoryScalarWhereInput'][] | null; // [StoryScalarWhereInput!]
    disconnect?: NexusGenInputs['StoryWhereUniqueInput'][] | null; // [StoryWhereUniqueInput!]
    set?: NexusGenInputs['StoryWhereUniqueInput'][] | null; // [StoryWhereUniqueInput!]
    update?: NexusGenInputs['StoryUpdateWithWhereUniqueWithoutSeriesInput'][] | null; // [StoryUpdateWithWhereUniqueWithoutSeriesInput!]
    updateMany?: NexusGenInputs['StoryUpdateManyWithWhereWithoutSeriesInput'][] | null; // [StoryUpdateManyWithWhereWithoutSeriesInput!]
    upsert?: NexusGenInputs['StoryUpsertWithWhereUniqueWithoutSeriesInput'][] | null; // [StoryUpsertWithWhereUniqueWithoutSeriesInput!]
  }
  StoryUpdateOneRequiredWithoutCharactersInput: { // input type
    connect?: NexusGenInputs['StoryWhereUniqueInput'] | null; // StoryWhereUniqueInput
    connectOrCreate?: NexusGenInputs['StoryCreateOrConnectWithoutCharactersInput'] | null; // StoryCreateOrConnectWithoutCharactersInput
    create?: NexusGenInputs['StoryCreateWithoutCharactersInput'] | null; // StoryCreateWithoutCharactersInput
    update?: NexusGenInputs['StoryUpdateWithoutCharactersInput'] | null; // StoryUpdateWithoutCharactersInput
    upsert?: NexusGenInputs['StoryUpsertWithoutCharactersInput'] | null; // StoryUpsertWithoutCharactersInput
  }
  StoryUpdateWithWhereUniqueWithoutAuthorInput: { // input type
    data: NexusGenInputs['StoryUpdateWithoutAuthorInput']; // StoryUpdateWithoutAuthorInput!
    where: NexusGenInputs['StoryWhereUniqueInput']; // StoryWhereUniqueInput!
  }
  StoryUpdateWithWhereUniqueWithoutSeriesInput: { // input type
    data: NexusGenInputs['StoryUpdateWithoutSeriesInput']; // StoryUpdateWithoutSeriesInput!
    where: NexusGenInputs['StoryWhereUniqueInput']; // StoryWhereUniqueInput!
  }
  StoryUpdateWithoutAuthorInput: { // input type
    characters?: NexusGenInputs['CharacterUpdateManyWithoutStoryInput'] | null; // CharacterUpdateManyWithoutStoryInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    part?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    private?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    series?: NexusGenInputs['SeriesUpdateOneWithoutStoriesInput'] | null; // SeriesUpdateOneWithoutStoriesInput
    subTitle?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    thumbnail?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  StoryUpdateWithoutCharactersInput: { // input type
    author?: NexusGenInputs['UserUpdateOneRequiredWithoutStoriesInput'] | null; // UserUpdateOneRequiredWithoutStoriesInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    part?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    private?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    series?: NexusGenInputs['SeriesUpdateOneWithoutStoriesInput'] | null; // SeriesUpdateOneWithoutStoriesInput
    subTitle?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    thumbnail?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  StoryUpdateWithoutSeriesInput: { // input type
    author?: NexusGenInputs['UserUpdateOneRequiredWithoutStoriesInput'] | null; // UserUpdateOneRequiredWithoutStoriesInput
    characters?: NexusGenInputs['CharacterUpdateManyWithoutStoryInput'] | null; // CharacterUpdateManyWithoutStoryInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    part?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    private?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    subTitle?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    thumbnail?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  StoryUpsertWithWhereUniqueWithoutAuthorInput: { // input type
    create: NexusGenInputs['StoryCreateWithoutAuthorInput']; // StoryCreateWithoutAuthorInput!
    update: NexusGenInputs['StoryUpdateWithoutAuthorInput']; // StoryUpdateWithoutAuthorInput!
    where: NexusGenInputs['StoryWhereUniqueInput']; // StoryWhereUniqueInput!
  }
  StoryUpsertWithWhereUniqueWithoutSeriesInput: { // input type
    create: NexusGenInputs['StoryCreateWithoutSeriesInput']; // StoryCreateWithoutSeriesInput!
    update: NexusGenInputs['StoryUpdateWithoutSeriesInput']; // StoryUpdateWithoutSeriesInput!
    where: NexusGenInputs['StoryWhereUniqueInput']; // StoryWhereUniqueInput!
  }
  StoryUpsertWithoutCharactersInput: { // input type
    create: NexusGenInputs['StoryCreateWithoutCharactersInput']; // StoryCreateWithoutCharactersInput!
    update: NexusGenInputs['StoryUpdateWithoutCharactersInput']; // StoryUpdateWithoutCharactersInput!
  }
  StoryWhereInput: { // input type
    AND?: NexusGenInputs['StoryWhereInput'][] | null; // [StoryWhereInput!]
    author?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    authorId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    characters?: NexusGenInputs['CharacterListRelationFilter'] | null; // CharacterListRelationFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    description?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: NexusGenInputs['StoryWhereInput'][] | null; // [StoryWhereInput!]
    OR?: NexusGenInputs['StoryWhereInput'][] | null; // [StoryWhereInput!]
    part?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    private?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    published?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    series?: NexusGenInputs['SeriesWhereInput'] | null; // SeriesWhereInput
    seriesId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    subTitle?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    thumbnail?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  StoryWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  UserCreateInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email?: string | null; // String
    emailVerified?: NexusGenScalars['DateTime'] | null; // DateTime
    image?: string | null; // String
    name?: string | null; // String
    stories?: NexusGenInputs['StoryCreateNestedManyWithoutAuthorInput'] | null; // StoryCreateNestedManyWithoutAuthorInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserCreateNestedOneWithoutStoriesInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutStoriesInput'] | null; // UserCreateOrConnectWithoutStoriesInput
    create?: NexusGenInputs['UserCreateWithoutStoriesInput'] | null; // UserCreateWithoutStoriesInput
  }
  UserCreateOrConnectWithoutStoriesInput: { // input type
    create: NexusGenInputs['UserCreateWithoutStoriesInput']; // UserCreateWithoutStoriesInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserCreateWithoutStoriesInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email?: string | null; // String
    emailVerified?: NexusGenScalars['DateTime'] | null; // DateTime
    image?: string | null; // String
    name?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserOrderByInput: { // input type
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    email?: NexusGenEnums['SortOrder'] | null; // SortOrder
    emailVerified?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    image?: NexusGenEnums['SortOrder'] | null; // SortOrder
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  UserUpdateInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    emailVerified?: NexusGenInputs['NullableDateTimeFieldUpdateOperationsInput'] | null; // NullableDateTimeFieldUpdateOperationsInput
    image?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    stories?: NexusGenInputs['StoryUpdateManyWithoutAuthorInput'] | null; // StoryUpdateManyWithoutAuthorInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  UserUpdateManyMutationInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    emailVerified?: NexusGenInputs['NullableDateTimeFieldUpdateOperationsInput'] | null; // NullableDateTimeFieldUpdateOperationsInput
    image?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  UserUpdateOneRequiredWithoutStoriesInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutStoriesInput'] | null; // UserCreateOrConnectWithoutStoriesInput
    create?: NexusGenInputs['UserCreateWithoutStoriesInput'] | null; // UserCreateWithoutStoriesInput
    update?: NexusGenInputs['UserUpdateWithoutStoriesInput'] | null; // UserUpdateWithoutStoriesInput
    upsert?: NexusGenInputs['UserUpsertWithoutStoriesInput'] | null; // UserUpsertWithoutStoriesInput
  }
  UserUpdateWithoutStoriesInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    emailVerified?: NexusGenInputs['NullableDateTimeFieldUpdateOperationsInput'] | null; // NullableDateTimeFieldUpdateOperationsInput
    image?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  UserUpsertWithoutStoriesInput: { // input type
    create: NexusGenInputs['UserCreateWithoutStoriesInput']; // UserCreateWithoutStoriesInput!
    update: NexusGenInputs['UserUpdateWithoutStoriesInput']; // UserUpdateWithoutStoriesInput!
  }
  UserWhereInput: { // input type
    AND?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    email?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    emailVerified?: NexusGenInputs['DateTimeNullableFilter'] | null; // DateTimeNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    image?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    NOT?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    OR?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    stories?: NexusGenInputs['StoryListRelationFilter'] | null; // StoryListRelationFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  UserWhereUniqueInput: { // input type
    email?: string | null; // String
    id?: number | null; // Int
  }
  VerificationRequestCreateInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    expires: NexusGenScalars['DateTime']; // DateTime!
    identifier: string; // String!
    token: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  VerificationRequestOrderByInput: { // input type
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    expires?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    identifier?: NexusGenEnums['SortOrder'] | null; // SortOrder
    token?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  VerificationRequestUpdateInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    expires?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    identifier?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    token?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  VerificationRequestUpdateManyMutationInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    expires?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    identifier?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    token?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  VerificationRequestWhereInput: { // input type
    AND?: NexusGenInputs['VerificationRequestWhereInput'][] | null; // [VerificationRequestWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    expires?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    identifier?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: NexusGenInputs['VerificationRequestWhereInput'][] | null; // [VerificationRequestWhereInput!]
    OR?: NexusGenInputs['VerificationRequestWhereInput'][] | null; // [VerificationRequestWhereInput!]
    token?: NexusGenInputs['StringFilter'] | null; // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  VerificationRequestWhereUniqueInput: { // input type
    id?: number | null; // Int
    token?: string | null; // String
  }
}

export interface NexusGenEnums {
  QueryMode: "default" | "insensitive"
  SortOrder: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Account: { // root type
    accessToken?: string | null; // String
    accessTokenExpires?: NexusGenScalars['DateTime'] | null; // DateTime
    compoundId: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    providerAccountId: string; // String!
    providerId: string; // String!
    providerType: string; // String!
    refreshToken?: string | null; // String
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    userId: number; // Int!
  }
  AffectedRowsOutput: { // root type
    count: number; // Int!
  }
  Character: { // root type
    age?: number | null; // Int
    bloodType?: string | null; // String
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description?: string | null; // String
    eyes?: string | null; // String
    height?: string | null; // String
    id: number; // Int!
    name?: string | null; // String
    published: boolean; // Boolean!
    storyId: number; // Int!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    weight?: string | null; // String
  }
  Example: { // root type
    message?: string | null; // String
  }
  Mutation: {};
  Query: {};
  Series: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description?: string | null; // String
    id: number; // Int!
    published: boolean; // Boolean!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Session: { // root type
    accessToken: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    expires: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    sessionToken: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    userId: number; // Int!
  }
  Story: { // root type
    authorId: number; // Int!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description?: string | null; // String
    id: number; // Int!
    part?: number | null; // Int
    private: boolean; // Boolean!
    published: boolean; // Boolean!
    seriesId?: number | null; // Int
    subTitle?: string | null; // String
    thumbnail?: string | null; // String
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  User: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    email?: string | null; // String
    emailVerified?: NexusGenScalars['DateTime'] | null; // DateTime
    id: number; // Int!
    image?: string | null; // String
    name?: string | null; // String
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  VerificationRequest: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    expires: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    identifier: string; // String!
    token: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Account: { // field return type
    accessToken: string | null; // String
    accessTokenExpires: NexusGenScalars['DateTime'] | null; // DateTime
    compoundId: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    providerAccountId: string; // String!
    providerId: string; // String!
    providerType: string; // String!
    refreshToken: string | null; // String
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    userId: number; // Int!
  }
  AffectedRowsOutput: { // field return type
    count: number; // Int!
  }
  Character: { // field return type
    age: number | null; // Int
    bloodType: string | null; // String
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string | null; // String
    eyes: string | null; // String
    height: string | null; // String
    id: number; // Int!
    name: string | null; // String
    published: boolean; // Boolean!
    story: NexusGenRootTypes['Story']; // Story!
    storyId: number; // Int!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    weight: string | null; // String
  }
  Example: { // field return type
    message: string | null; // String
  }
  Mutation: { // field return type
    createOneAccount: NexusGenRootTypes['Account']; // Account!
    createOneCharacter: NexusGenRootTypes['Character']; // Character!
    createOneSeries: NexusGenRootTypes['Series']; // Series!
    createOneSession: NexusGenRootTypes['Session']; // Session!
    createOneStory: NexusGenRootTypes['Story']; // Story!
    createOneUser: NexusGenRootTypes['User']; // User!
    createOneVerificationRequest: NexusGenRootTypes['VerificationRequest']; // VerificationRequest!
    deleteManyAccount: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    deleteManyCharacter: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    deleteManySeries: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    deleteManySession: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    deleteManyStory: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    deleteManyUser: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    deleteManyVerificationRequest: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    deleteOneAccount: NexusGenRootTypes['Account'] | null; // Account
    deleteOneCharacter: NexusGenRootTypes['Character'] | null; // Character
    deleteOneSeries: NexusGenRootTypes['Series'] | null; // Series
    deleteOneSession: NexusGenRootTypes['Session'] | null; // Session
    deleteOneStory: NexusGenRootTypes['Story'] | null; // Story
    deleteOneUser: NexusGenRootTypes['User'] | null; // User
    deleteOneVerificationRequest: NexusGenRootTypes['VerificationRequest'] | null; // VerificationRequest
    updateManyAccount: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    updateManyCharacter: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    updateManySeries: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    updateManySession: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    updateManyStory: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    updateManyUser: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    updateManyVerificationRequest: NexusGenRootTypes['AffectedRowsOutput']; // AffectedRowsOutput!
    updateOneAccount: NexusGenRootTypes['Account'] | null; // Account
    updateOneCharacter: NexusGenRootTypes['Character'] | null; // Character
    updateOneSeries: NexusGenRootTypes['Series'] | null; // Series
    updateOneSession: NexusGenRootTypes['Session'] | null; // Session
    updateOneStory: NexusGenRootTypes['Story'] | null; // Story
    updateOneUser: NexusGenRootTypes['User'] | null; // User
    updateOneVerificationRequest: NexusGenRootTypes['VerificationRequest'] | null; // VerificationRequest
    upsertOneAccount: NexusGenRootTypes['Account']; // Account!
    upsertOneCharacter: NexusGenRootTypes['Character']; // Character!
    upsertOneSeries: NexusGenRootTypes['Series']; // Series!
    upsertOneSession: NexusGenRootTypes['Session']; // Session!
    upsertOneStory: NexusGenRootTypes['Story']; // Story!
    upsertOneUser: NexusGenRootTypes['User']; // User!
    upsertOneVerificationRequest: NexusGenRootTypes['VerificationRequest']; // VerificationRequest!
  }
  Query: { // field return type
    account: NexusGenRootTypes['Account'] | null; // Account
    accounts: NexusGenRootTypes['Account'][]; // [Account!]!
    accountsCount: number | null; // Int
    character: NexusGenRootTypes['Character'] | null; // Character
    characters: NexusGenRootTypes['Character'][]; // [Character!]!
    charactersCount: number | null; // Int
    example: NexusGenRootTypes['Example'] | null; // Example
    findFirstAccount: NexusGenRootTypes['Account'] | null; // Account
    findFirstCharacter: NexusGenRootTypes['Character'] | null; // Character
    findFirstSeries: NexusGenRootTypes['Series'] | null; // Series
    findFirstSession: NexusGenRootTypes['Session'] | null; // Session
    findFirstStory: NexusGenRootTypes['Story'] | null; // Story
    findFirstUser: NexusGenRootTypes['User'] | null; // User
    findFirstVerificationRequest: NexusGenRootTypes['VerificationRequest'] | null; // VerificationRequest
    series: NexusGenRootTypes['Series'][]; // [Series!]!
    seriesCount: number | null; // Int
    session: NexusGenRootTypes['Session'] | null; // Session
    sessions: NexusGenRootTypes['Session'][]; // [Session!]!
    sessionsCount: number | null; // Int
    stories: NexusGenRootTypes['Story'][]; // [Story!]!
    storiesCount: number | null; // Int
    story: NexusGenRootTypes['Story'] | null; // Story
    user: NexusGenRootTypes['User'] | null; // User
    users: NexusGenRootTypes['User'][]; // [User!]!
    usersCount: number | null; // Int
    verificationRequest: NexusGenRootTypes['VerificationRequest'] | null; // VerificationRequest
    verificationRequests: NexusGenRootTypes['VerificationRequest'][]; // [VerificationRequest!]!
    verificationRequestsCount: number | null; // Int
  }
  Series: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string | null; // String
    id: number; // Int!
    published: boolean; // Boolean!
    stories: NexusGenRootTypes['Story'][]; // [Story!]!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Session: { // field return type
    accessToken: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    expires: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    sessionToken: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    userId: number; // Int!
  }
  Story: { // field return type
    author: NexusGenRootTypes['User']; // User!
    authorId: number; // Int!
    characters: NexusGenRootTypes['Character'][]; // [Character!]!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string | null; // String
    id: number; // Int!
    part: number | null; // Int
    private: boolean; // Boolean!
    published: boolean; // Boolean!
    series: NexusGenRootTypes['Series'] | null; // Series
    seriesId: number | null; // Int
    subTitle: string | null; // String
    thumbnail: string | null; // String
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  User: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    email: string | null; // String
    emailVerified: NexusGenScalars['DateTime'] | null; // DateTime
    id: number; // Int!
    image: string | null; // String
    name: string | null; // String
    stories: NexusGenRootTypes['Story'][]; // [Story!]!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  VerificationRequest: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    expires: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    identifier: string; // String!
    token: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
}

export interface NexusGenFieldTypeNames {
  Account: { // field return type name
    accessToken: 'String'
    accessTokenExpires: 'DateTime'
    compoundId: 'String'
    createdAt: 'DateTime'
    id: 'Int'
    providerAccountId: 'String'
    providerId: 'String'
    providerType: 'String'
    refreshToken: 'String'
    updatedAt: 'DateTime'
    userId: 'Int'
  }
  AffectedRowsOutput: { // field return type name
    count: 'Int'
  }
  Character: { // field return type name
    age: 'Int'
    bloodType: 'String'
    createdAt: 'DateTime'
    description: 'String'
    eyes: 'String'
    height: 'String'
    id: 'Int'
    name: 'String'
    published: 'Boolean'
    story: 'Story'
    storyId: 'Int'
    updatedAt: 'DateTime'
    weight: 'String'
  }
  Example: { // field return type name
    message: 'String'
  }
  Mutation: { // field return type name
    createOneAccount: 'Account'
    createOneCharacter: 'Character'
    createOneSeries: 'Series'
    createOneSession: 'Session'
    createOneStory: 'Story'
    createOneUser: 'User'
    createOneVerificationRequest: 'VerificationRequest'
    deleteManyAccount: 'AffectedRowsOutput'
    deleteManyCharacter: 'AffectedRowsOutput'
    deleteManySeries: 'AffectedRowsOutput'
    deleteManySession: 'AffectedRowsOutput'
    deleteManyStory: 'AffectedRowsOutput'
    deleteManyUser: 'AffectedRowsOutput'
    deleteManyVerificationRequest: 'AffectedRowsOutput'
    deleteOneAccount: 'Account'
    deleteOneCharacter: 'Character'
    deleteOneSeries: 'Series'
    deleteOneSession: 'Session'
    deleteOneStory: 'Story'
    deleteOneUser: 'User'
    deleteOneVerificationRequest: 'VerificationRequest'
    updateManyAccount: 'AffectedRowsOutput'
    updateManyCharacter: 'AffectedRowsOutput'
    updateManySeries: 'AffectedRowsOutput'
    updateManySession: 'AffectedRowsOutput'
    updateManyStory: 'AffectedRowsOutput'
    updateManyUser: 'AffectedRowsOutput'
    updateManyVerificationRequest: 'AffectedRowsOutput'
    updateOneAccount: 'Account'
    updateOneCharacter: 'Character'
    updateOneSeries: 'Series'
    updateOneSession: 'Session'
    updateOneStory: 'Story'
    updateOneUser: 'User'
    updateOneVerificationRequest: 'VerificationRequest'
    upsertOneAccount: 'Account'
    upsertOneCharacter: 'Character'
    upsertOneSeries: 'Series'
    upsertOneSession: 'Session'
    upsertOneStory: 'Story'
    upsertOneUser: 'User'
    upsertOneVerificationRequest: 'VerificationRequest'
  }
  Query: { // field return type name
    account: 'Account'
    accounts: 'Account'
    accountsCount: 'Int'
    character: 'Character'
    characters: 'Character'
    charactersCount: 'Int'
    example: 'Example'
    findFirstAccount: 'Account'
    findFirstCharacter: 'Character'
    findFirstSeries: 'Series'
    findFirstSession: 'Session'
    findFirstStory: 'Story'
    findFirstUser: 'User'
    findFirstVerificationRequest: 'VerificationRequest'
    series: 'Series'
    seriesCount: 'Int'
    session: 'Session'
    sessions: 'Session'
    sessionsCount: 'Int'
    stories: 'Story'
    storiesCount: 'Int'
    story: 'Story'
    user: 'User'
    users: 'User'
    usersCount: 'Int'
    verificationRequest: 'VerificationRequest'
    verificationRequests: 'VerificationRequest'
    verificationRequestsCount: 'Int'
  }
  Series: { // field return type name
    createdAt: 'DateTime'
    description: 'String'
    id: 'Int'
    published: 'Boolean'
    stories: 'Story'
    title: 'String'
    updatedAt: 'DateTime'
  }
  Session: { // field return type name
    accessToken: 'String'
    createdAt: 'DateTime'
    expires: 'DateTime'
    id: 'Int'
    sessionToken: 'String'
    updatedAt: 'DateTime'
    userId: 'Int'
  }
  Story: { // field return type name
    author: 'User'
    authorId: 'Int'
    characters: 'Character'
    createdAt: 'DateTime'
    description: 'String'
    id: 'Int'
    part: 'Int'
    private: 'Boolean'
    published: 'Boolean'
    series: 'Series'
    seriesId: 'Int'
    subTitle: 'String'
    thumbnail: 'String'
    title: 'String'
    updatedAt: 'DateTime'
  }
  User: { // field return type name
    createdAt: 'DateTime'
    email: 'String'
    emailVerified: 'DateTime'
    id: 'Int'
    image: 'String'
    name: 'String'
    stories: 'Story'
    updatedAt: 'DateTime'
  }
  VerificationRequest: { // field return type name
    createdAt: 'DateTime'
    expires: 'DateTime'
    id: 'Int'
    identifier: 'String'
    token: 'String'
    updatedAt: 'DateTime'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOneAccount: { // args
      data: NexusGenInputs['AccountCreateInput']; // AccountCreateInput!
    }
    createOneCharacter: { // args
      data: NexusGenInputs['CharacterCreateInput']; // CharacterCreateInput!
    }
    createOneSeries: { // args
      data: NexusGenInputs['SeriesCreateInput']; // SeriesCreateInput!
    }
    createOneSession: { // args
      data: NexusGenInputs['SessionCreateInput']; // SessionCreateInput!
    }
    createOneStory: { // args
      data: NexusGenInputs['StoryCreateInput']; // StoryCreateInput!
    }
    createOneUser: { // args
      data: NexusGenInputs['UserCreateInput']; // UserCreateInput!
    }
    createOneVerificationRequest: { // args
      data: NexusGenInputs['VerificationRequestCreateInput']; // VerificationRequestCreateInput!
    }
    deleteManyAccount: { // args
      where?: NexusGenInputs['AccountWhereInput'] | null; // AccountWhereInput
    }
    deleteManyCharacter: { // args
      where?: NexusGenInputs['CharacterWhereInput'] | null; // CharacterWhereInput
    }
    deleteManySeries: { // args
      where?: NexusGenInputs['SeriesWhereInput'] | null; // SeriesWhereInput
    }
    deleteManySession: { // args
      where?: NexusGenInputs['SessionWhereInput'] | null; // SessionWhereInput
    }
    deleteManyStory: { // args
      where?: NexusGenInputs['StoryWhereInput'] | null; // StoryWhereInput
    }
    deleteManyUser: { // args
      where?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    }
    deleteManyVerificationRequest: { // args
      where?: NexusGenInputs['VerificationRequestWhereInput'] | null; // VerificationRequestWhereInput
    }
    deleteOneAccount: { // args
      where: NexusGenInputs['AccountWhereUniqueInput']; // AccountWhereUniqueInput!
    }
    deleteOneCharacter: { // args
      where: NexusGenInputs['CharacterWhereUniqueInput']; // CharacterWhereUniqueInput!
    }
    deleteOneSeries: { // args
      where: NexusGenInputs['SeriesWhereUniqueInput']; // SeriesWhereUniqueInput!
    }
    deleteOneSession: { // args
      where: NexusGenInputs['SessionWhereUniqueInput']; // SessionWhereUniqueInput!
    }
    deleteOneStory: { // args
      where: NexusGenInputs['StoryWhereUniqueInput']; // StoryWhereUniqueInput!
    }
    deleteOneUser: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
    deleteOneVerificationRequest: { // args
      where: NexusGenInputs['VerificationRequestWhereUniqueInput']; // VerificationRequestWhereUniqueInput!
    }
    updateManyAccount: { // args
      data: NexusGenInputs['AccountUpdateManyMutationInput']; // AccountUpdateManyMutationInput!
      where?: NexusGenInputs['AccountWhereInput'] | null; // AccountWhereInput
    }
    updateManyCharacter: { // args
      data: NexusGenInputs['CharacterUpdateManyMutationInput']; // CharacterUpdateManyMutationInput!
      where?: NexusGenInputs['CharacterWhereInput'] | null; // CharacterWhereInput
    }
    updateManySeries: { // args
      data: NexusGenInputs['SeriesUpdateManyMutationInput']; // SeriesUpdateManyMutationInput!
      where?: NexusGenInputs['SeriesWhereInput'] | null; // SeriesWhereInput
    }
    updateManySession: { // args
      data: NexusGenInputs['SessionUpdateManyMutationInput']; // SessionUpdateManyMutationInput!
      where?: NexusGenInputs['SessionWhereInput'] | null; // SessionWhereInput
    }
    updateManyStory: { // args
      data: NexusGenInputs['StoryUpdateManyMutationInput']; // StoryUpdateManyMutationInput!
      where?: NexusGenInputs['StoryWhereInput'] | null; // StoryWhereInput
    }
    updateManyUser: { // args
      data: NexusGenInputs['UserUpdateManyMutationInput']; // UserUpdateManyMutationInput!
      where?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    }
    updateManyVerificationRequest: { // args
      data: NexusGenInputs['VerificationRequestUpdateManyMutationInput']; // VerificationRequestUpdateManyMutationInput!
      where?: NexusGenInputs['VerificationRequestWhereInput'] | null; // VerificationRequestWhereInput
    }
    updateOneAccount: { // args
      data: NexusGenInputs['AccountUpdateInput']; // AccountUpdateInput!
      where: NexusGenInputs['AccountWhereUniqueInput']; // AccountWhereUniqueInput!
    }
    updateOneCharacter: { // args
      data: NexusGenInputs['CharacterUpdateInput']; // CharacterUpdateInput!
      where: NexusGenInputs['CharacterWhereUniqueInput']; // CharacterWhereUniqueInput!
    }
    updateOneSeries: { // args
      data: NexusGenInputs['SeriesUpdateInput']; // SeriesUpdateInput!
      where: NexusGenInputs['SeriesWhereUniqueInput']; // SeriesWhereUniqueInput!
    }
    updateOneSession: { // args
      data: NexusGenInputs['SessionUpdateInput']; // SessionUpdateInput!
      where: NexusGenInputs['SessionWhereUniqueInput']; // SessionWhereUniqueInput!
    }
    updateOneStory: { // args
      data: NexusGenInputs['StoryUpdateInput']; // StoryUpdateInput!
      where: NexusGenInputs['StoryWhereUniqueInput']; // StoryWhereUniqueInput!
    }
    updateOneUser: { // args
      data: NexusGenInputs['UserUpdateInput']; // UserUpdateInput!
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
    updateOneVerificationRequest: { // args
      data: NexusGenInputs['VerificationRequestUpdateInput']; // VerificationRequestUpdateInput!
      where: NexusGenInputs['VerificationRequestWhereUniqueInput']; // VerificationRequestWhereUniqueInput!
    }
    upsertOneAccount: { // args
      create: NexusGenInputs['AccountCreateInput']; // AccountCreateInput!
      update: NexusGenInputs['AccountUpdateInput']; // AccountUpdateInput!
      where: NexusGenInputs['AccountWhereUniqueInput']; // AccountWhereUniqueInput!
    }
    upsertOneCharacter: { // args
      create: NexusGenInputs['CharacterCreateInput']; // CharacterCreateInput!
      update: NexusGenInputs['CharacterUpdateInput']; // CharacterUpdateInput!
      where: NexusGenInputs['CharacterWhereUniqueInput']; // CharacterWhereUniqueInput!
    }
    upsertOneSeries: { // args
      create: NexusGenInputs['SeriesCreateInput']; // SeriesCreateInput!
      update: NexusGenInputs['SeriesUpdateInput']; // SeriesUpdateInput!
      where: NexusGenInputs['SeriesWhereUniqueInput']; // SeriesWhereUniqueInput!
    }
    upsertOneSession: { // args
      create: NexusGenInputs['SessionCreateInput']; // SessionCreateInput!
      update: NexusGenInputs['SessionUpdateInput']; // SessionUpdateInput!
      where: NexusGenInputs['SessionWhereUniqueInput']; // SessionWhereUniqueInput!
    }
    upsertOneStory: { // args
      create: NexusGenInputs['StoryCreateInput']; // StoryCreateInput!
      update: NexusGenInputs['StoryUpdateInput']; // StoryUpdateInput!
      where: NexusGenInputs['StoryWhereUniqueInput']; // StoryWhereUniqueInput!
    }
    upsertOneUser: { // args
      create: NexusGenInputs['UserCreateInput']; // UserCreateInput!
      update: NexusGenInputs['UserUpdateInput']; // UserUpdateInput!
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
    upsertOneVerificationRequest: { // args
      create: NexusGenInputs['VerificationRequestCreateInput']; // VerificationRequestCreateInput!
      update: NexusGenInputs['VerificationRequestUpdateInput']; // VerificationRequestUpdateInput!
      where: NexusGenInputs['VerificationRequestWhereUniqueInput']; // VerificationRequestWhereUniqueInput!
    }
  }
  Query: {
    account: { // args
      where: NexusGenInputs['AccountWhereUniqueInput']; // AccountWhereUniqueInput!
    }
    accounts: { // args
      after?: NexusGenInputs['AccountWhereUniqueInput'] | null; // AccountWhereUniqueInput
      before?: NexusGenInputs['AccountWhereUniqueInput'] | null; // AccountWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['AccountOrderByInput'][] | null; // [AccountOrderByInput!]
      where?: NexusGenInputs['AccountWhereInput'] | null; // AccountWhereInput
    }
    accountsCount: { // args
      where?: NexusGenInputs['AccountWhereInput'] | null; // AccountWhereInput
    }
    character: { // args
      where: NexusGenInputs['CharacterWhereUniqueInput']; // CharacterWhereUniqueInput!
    }
    characters: { // args
      after?: NexusGenInputs['CharacterWhereUniqueInput'] | null; // CharacterWhereUniqueInput
      before?: NexusGenInputs['CharacterWhereUniqueInput'] | null; // CharacterWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['CharacterOrderByInput'][] | null; // [CharacterOrderByInput!]
      where?: NexusGenInputs['CharacterWhereInput'] | null; // CharacterWhereInput
    }
    charactersCount: { // args
      where?: NexusGenInputs['CharacterWhereInput'] | null; // CharacterWhereInput
    }
    findFirstAccount: { // args
      cursor?: NexusGenInputs['AccountWhereUniqueInput'] | null; // AccountWhereUniqueInput
      orderBy?: NexusGenInputs['AccountOrderByInput'] | null; // AccountOrderByInput
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['AccountWhereInput'] | null; // AccountWhereInput
    }
    findFirstCharacter: { // args
      cursor?: NexusGenInputs['CharacterWhereUniqueInput'] | null; // CharacterWhereUniqueInput
      orderBy?: NexusGenInputs['CharacterOrderByInput'] | null; // CharacterOrderByInput
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['CharacterWhereInput'] | null; // CharacterWhereInput
    }
    findFirstSeries: { // args
      cursor?: NexusGenInputs['SeriesWhereUniqueInput'] | null; // SeriesWhereUniqueInput
      orderBy?: NexusGenInputs['SeriesOrderByInput'] | null; // SeriesOrderByInput
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['SeriesWhereInput'] | null; // SeriesWhereInput
    }
    findFirstSession: { // args
      cursor?: NexusGenInputs['SessionWhereUniqueInput'] | null; // SessionWhereUniqueInput
      orderBy?: NexusGenInputs['SessionOrderByInput'] | null; // SessionOrderByInput
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['SessionWhereInput'] | null; // SessionWhereInput
    }
    findFirstStory: { // args
      cursor?: NexusGenInputs['StoryWhereUniqueInput'] | null; // StoryWhereUniqueInput
      orderBy?: NexusGenInputs['StoryOrderByInput'] | null; // StoryOrderByInput
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['StoryWhereInput'] | null; // StoryWhereInput
    }
    findFirstUser: { // args
      cursor?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      orderBy?: NexusGenInputs['UserOrderByInput'] | null; // UserOrderByInput
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    }
    findFirstVerificationRequest: { // args
      cursor?: NexusGenInputs['VerificationRequestWhereUniqueInput'] | null; // VerificationRequestWhereUniqueInput
      orderBy?: NexusGenInputs['VerificationRequestOrderByInput'] | null; // VerificationRequestOrderByInput
      skip?: number | null; // Int
      take?: number | null; // Int
      where?: NexusGenInputs['VerificationRequestWhereInput'] | null; // VerificationRequestWhereInput
    }
    series: { // args
      after?: NexusGenInputs['SeriesWhereUniqueInput'] | null; // SeriesWhereUniqueInput
      before?: NexusGenInputs['SeriesWhereUniqueInput'] | null; // SeriesWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['SeriesOrderByInput'][] | null; // [SeriesOrderByInput!]
      where?: NexusGenInputs['SeriesWhereInput'] | null; // SeriesWhereInput
    }
    seriesCount: { // args
      where?: NexusGenInputs['SeriesWhereInput'] | null; // SeriesWhereInput
    }
    session: { // args
      where: NexusGenInputs['SessionWhereUniqueInput']; // SessionWhereUniqueInput!
    }
    sessions: { // args
      after?: NexusGenInputs['SessionWhereUniqueInput'] | null; // SessionWhereUniqueInput
      before?: NexusGenInputs['SessionWhereUniqueInput'] | null; // SessionWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['SessionOrderByInput'][] | null; // [SessionOrderByInput!]
      where?: NexusGenInputs['SessionWhereInput'] | null; // SessionWhereInput
    }
    sessionsCount: { // args
      where?: NexusGenInputs['SessionWhereInput'] | null; // SessionWhereInput
    }
    stories: { // args
      after?: NexusGenInputs['StoryWhereUniqueInput'] | null; // StoryWhereUniqueInput
      before?: NexusGenInputs['StoryWhereUniqueInput'] | null; // StoryWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['StoryOrderByInput'][] | null; // [StoryOrderByInput!]
      where?: NexusGenInputs['StoryWhereInput'] | null; // StoryWhereInput
    }
    storiesCount: { // args
      where?: NexusGenInputs['StoryWhereInput'] | null; // StoryWhereInput
    }
    story: { // args
      where: NexusGenInputs['StoryWhereUniqueInput']; // StoryWhereUniqueInput!
    }
    user: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
    users: { // args
      after?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      before?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['UserOrderByInput'][] | null; // [UserOrderByInput!]
      where?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    }
    usersCount: { // args
      where?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    }
    verificationRequest: { // args
      where: NexusGenInputs['VerificationRequestWhereUniqueInput']; // VerificationRequestWhereUniqueInput!
    }
    verificationRequests: { // args
      after?: NexusGenInputs['VerificationRequestWhereUniqueInput'] | null; // VerificationRequestWhereUniqueInput
      before?: NexusGenInputs['VerificationRequestWhereUniqueInput'] | null; // VerificationRequestWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['VerificationRequestOrderByInput'][] | null; // [VerificationRequestOrderByInput!]
      where?: NexusGenInputs['VerificationRequestWhereInput'] | null; // VerificationRequestWhereInput
    }
    verificationRequestsCount: { // args
      where?: NexusGenInputs['VerificationRequestWhereInput'] | null; // VerificationRequestWhereInput
    }
  }
  Series: {
    stories: { // args
      after?: NexusGenInputs['StoryWhereUniqueInput'] | null; // StoryWhereUniqueInput
      before?: NexusGenInputs['StoryWhereUniqueInput'] | null; // StoryWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Story: {
    characters: { // args
      after?: NexusGenInputs['CharacterWhereUniqueInput'] | null; // CharacterWhereUniqueInput
      before?: NexusGenInputs['CharacterWhereUniqueInput'] | null; // CharacterWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  User: {
    stories: { // args
      after?: NexusGenInputs['StoryWhereUniqueInput'] | null; // StoryWhereUniqueInput
      before?: NexusGenInputs['StoryWhereUniqueInput'] | null; // StoryWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}